global:
  domain: yas.local.com
  envTag: staging
  image:
    tag: rc_v1.0.0

backoffice-bff:
  backend:
    image:
      tag: rc_v1.0.0
backoffice-ui:
  ui:
    image:
      tag: rc_v1.0.0
cart:
  backend:
    image:
      tag: rc_v1.0.0
customer:
  backend:
    image:
      tag: rc_v1.0.0
inventory:
  backend:
    image:
      tag: rc_v1.0.0
location:
  backend:
    image:
      tag: rc_v1.0.0
media:
  backend:
    image:
      tag: rc_v1.0.0
order:
  backend:
    image:
      tag: rc_v1.0.0
payment:
  backend:
    image:
      tag: rc_v1.0.0
payment-paypal:
  backend:
    image:
      tag: rc_v1.0.0
product:
  backend:
    image:
      tag: rc_v1.0.0
promotion:
  backend:
    image:
      tag: rc_v1.0.0
rating:
  backend:
    image:
      tag: rc_v1.0.0
recommendation:
  backend:
    image:
      tag: rc_v1.0.0
sampledata:
  backend:
    image:
      tag: rc_v1.0.0
search:
  backend:
    image:
      tag: rc_v1.0.0
storefront-bff:
  backend:
    image:
      tag: rc_v1.0.0
storefront-ui:
  ui:
    image:
      tag: rc_v1.0.0
tax:
  backend:
    image:
      tag: rc_v1.0.0
webhook:
  backend:
    image:
      tag: rc_v1.0.0

# Cấu hình Data Layer (Postgres, Kafka, Keycloak, etc.)
postgresql:
  replicas: 1
  username: yasadminuser
  password: admin
pgadmin:
  hostname: pgadmin-staging.yas.local.com
zookeeper: {}
kafka-cluster:
  kafka:
    replicas: 1
  zookeeper:
    replicas: 1
  postgresql:
    username: yasadminuser
    password: admin
akhq:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      argocd.argoproj.io/sync-wave: "-20"
    hosts:
      - host: akhq-staging.yas.local.com
        paths:
          - path: /
            pathType: Prefix
  configuration:
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
        kafka-connection:
          properties:
            bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
          connect:
            - name: debezium-connect-cluster
              url: http://debezium-connect-cluster-connect-api:8083
elasticsearch-cluster:
  elasticsearch:
    replicas: 1
  kibana:
    ingress:
      hostname: kibana-staging.yas.local.com
redis:
  auth:
    password: redis
keycloak:
  hostname: identity-staging.yas.local.com
  postgresql:
    username: yasadminuser
    password: admin
  bootstrapAdmin:
    username: admin
    password: admin
  backofficeRedirectUrl: https://backoffice-staging.yas.local.com
  storefrontRedirectUrl: https://storefront-staging.yas.local.com
  apiRedirectUrl: https://api-staging.yas.local.com
